deploy-contract functional

diff --git a/tools/all-in-one/corda/builder/gradlew b/tools/all-in-one/corda/builder/gradlew
--- a/tools/all-in-one/corda/builder/gradlew
+++ b/tools/all-in-one/corda/builder/gradlew
@@ -65,28 +65,30 @@ case "`uname`" in
 esac
 
 CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar
-
+JAVA_HOME=/opt/java/openjdk/bin/java
+JAVACMD=/opt/java/openjdk/bin/java
+PATH=$PATH:/opt/java/openjdk/bin
 # Determine the Java command to use to start the JVM.
-if [ -n "$JAVA_HOME" ] ; then
-    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
-        # IBM's JDK on AIX uses strange locations for the executables
-        JAVACMD="$JAVA_HOME/jre/sh/java"
-    else
-        JAVACMD="$JAVA_HOME/bin/java"
-    fi
-    if [ ! -x "$JAVACMD" ] ; then
-        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME
+# if [ -n "$JAVA_HOME" ] ; then
+#     if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
+#         # IBM's JDK on AIX uses strange locations for the executables
+#         JAVACMD="$JAVA_HOME/jre/sh/java"
+#     else
+#         JAVACMD="$JAVA_HOME/bin/java"
+#     fi
+#     if [ ! -x "$JAVACMD" ] ; then
+#         die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME
 
-Please set the JAVA_HOME variable in your environment to match the
-location of your Java installation."
-    fi
-else
-    JAVACMD="java"
-    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
+# Please set the JAVA_HOME variable in your environment to match the
+# location of your Java installation."
+#     fi
+# else
+#     JAVACMD="java"
+#     which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
 
-Please set the JAVA_HOME variable in your environment to match the
-location of your Java installation."
-fi
+# Please set the JAVA_HOME variable in your environment to match the
+# location of your Java installation."
+# fi
 
 # Increase the maximum file descriptors if we can.
 if [ "$cygwin" = "false" -a "$darwin" = "false" -a "$nonstop" = "false" ] ; then
