ci: improve linter enforcement
Fixes flagged problems from yarn run lint including
-Fixing typos
-Adding cspell entries

Add yarn run lint to pre commit hooks

Signed-off-by: Rafael Belchior <rafael.belchior@tecnico.ulisboa.pt>

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,2 +1,7 @@
 #!/bin/sh
-#placeholder
+echo  "pre-commit hook, running yarn run lint"
+yarn run lint
+if [ $? -ne 0 ]; then
+	echo "Lint failed. Please fix errors before committing."
+	exit 1
+fi
