ci(all-nodejs-packages-publish): restrict job trigger pattern to semver Primary Changes ---------------- 1. Added semver validation to all-nodejs-packages-publish.yaml
Peter's Updates
-----------------

1. Pinned the GitHub Action version to an exact one: v4.0.5

Fixes #2385

Co-authored-by: Peter Somogyvari <peter.somogyvari@accenture.com>

Signed-off-by: adrianbatuto <adrian.batuto@accenture.com>
Signed-off-by: Peter Somogyvari <peter.somogyvari@accenture.com>

diff --git a/.github/workflows/all-nodejs-packages-publish.yaml b/.github/workflows/all-nodejs-packages-publish.yaml
--- a/.github/workflows/all-nodejs-packages-publish.yaml
+++ b/.github/workflows/all-nodejs-packages-publish.yaml
@@ -24,6 +24,18 @@ jobs:
     permissions: 
       id-token: write
     steps:
+      - name: Check Version Format in Tag
+        uses: nowsprinting/check-version-format-action@v4.0.5
+        id: version
+        with:
+          prefix: 'v'
+
+      - name: Fail if version is invalid
+        if: steps.version.outputs.is_valid != 'true'
+        run: |
+          echo "Error: Tag '${{ github.ref_name }}' is not a valid semantic version."
+          exit 1
+
       - name: Print Workflow inputs.GIT_TAG_TO_PUBLISH
         run: |
           echo "inputs.GIT_TAG_TO_PUBLISH=${{ inputs.GIT_TAG_TO_PUBLISH }}" 
