fix(weaver-go-sdk): revert fabric-protos-go-apiv2 dep to fabric-protos-go
    * Added a script to manually change go package names inside fabric-protos
      to fabric-protos-go-apiv2 (for future migration apiv2).
    * Added more unit and build tests covering all go modules
    * Added tools/go-mod-tidy.sh script to fix go.mod by running go mod tidy

Signed-off-by: Sandeep Nishad <sandeep.nishad1@ibm.com>

diff --git a/.github/workflows/test_weaver-go.yaml b/.github/workflows/test_weaver-go.yaml
--- a/.github/workflows/test_weaver-go.yaml
+++ b/.github/workflows/test_weaver-go.yaml
@@ -18,7 +18,10 @@ jobs:
   check_code_changed:
     outputs:
       interopcc_changed: ${{ steps.changes.outputs.interopcc_changed }}
+      gosdk_changed: ${{ steps.changes.outputs.gosdk_changed }}
+      gocli_changed: ${{ steps.changes.outputs.gocli_changed }}
       simplestate_changed: ${{ steps.changes.outputs.simplestate_changed }}
+      satpsimpleasset_changed: ${{ steps.changes.outputs.satpsimpleasset_changed }}
       simpleasset_changed: ${{ steps.changes.outputs.simpleasset_changed }}
       simpleassetandinterop_changed: ${{ steps.changes.outputs.simpleassetandinterop_changed }}
       simpleassettransfer_changed: ${{ steps.changes.outputs.simpleassettransfer_changed }}
@@ -35,8 +38,17 @@ jobs:
               - 'weaver/core/network/fabric-interop-cc/**'
               - '.github/workflows/test_weaver-go.yaml'
 
+            gosdk_changed:
+              - 'weaver/sdks/fabric/go-sdk/**'
+
+            gocli_changed:
+              - 'weaver/samples/fabric/go-cli/**'
+
             simplestate_changed:
               - 'weaver/samples/fabric/simplestate/**'
+
+            satpsimpleasset_changed:
+              - 'weaver/samples/fabric/satpsimpleasset/**'
 
             simpleasset_changed:
               - 'weaver/samples/fabric/simpleasset/**'
@@ -60,7 +72,7 @@ jobs:
         go-version: '1.20.2'
 
     - name: Vendor
-      run: make run-vendor
+      run: make run-vendor || echo "If this steps fails and asks to run 'go mod tidy' then run the script 'tools/go-mod-tidy.sh' to update all go modules"
       working-directory: weaver/core/network/fabric-interop-cc/contracts/interop
 
     - name: Build
@@ -95,6 +107,90 @@ jobs:
     - name: Test
       run: go test -v ./...
       working-directory: weaver/core/network/fabric-interop-cc/interfaces/asset-mgmt
+      
+  build_test_libs_utils:
+    needs: check_code_changed
+    if: needs.check_code_changed.outputs.interopcc_changed == 'true'
+    runs-on: ubuntu-22.04
+    steps:
+    - uses: actions/checkout@v4.1.1
+
+    - name: Set up Go
+      uses: actions/setup-go@v4.0.0
+      with:
+        go-version: '1.20.2'
+
+    - name: Vendor
+      run: make run-vendor
+      working-directory: weaver/core/network/fabric-interop-cc/libs/utils
+
+    - name: Build
+      run: go build -v ./...
+      working-directory: weaver/core/network/fabric-interop-cc/libs/utils
+      
+  build_test_libs_assetexchange:
+    needs: check_code_changed
+    if: needs.check_code_changed.outputs.interopcc_changed == 'true'
+    runs-on: ubuntu-22.04
+    steps:
+    - uses: actions/checkout@v4.1.1
+
+    - name: Set up Go
+      uses: actions/setup-go@v4.0.0
+      with:
+        go-version: '1.20.2'
+
+    - name: Vendor
+      run: make run-vendor
+      working-directory: weaver/core/network/fabric-interop-cc/libs/assetexchange
+
+    - name: Build
+      run: go build -v ./...
+      working-directory: weaver/core/network/fabric-interop-cc/libs/assetexchange
+      
+  unit_test_sdk:
+    needs: check_code_changed
+    if: ${{ needs.check_code_changed.outputs.interopcc_changed == 'true' || needs.check_code_changed.outputs.gosdk_changed   == 'true' }}
+    runs-on: ubuntu-22.04
+    steps:
+    - uses: actions/checkout@v4.1.1
+
+    - name: Set up Go
+      uses: actions/setup-go@v4.0.0
+      with:
+        go-version: '1.20.2'
+
+    - name: Vendor
+      run: make run-vendor
+      working-directory: weaver/sdks/fabric/go-sdk
+
+    - name: Build
+      run: make build
+      working-directory: weaver/sdks/fabric/go-sdk
+
+    - name: Test
+      run: make test
+      working-directory: weaver/sdks/fabric/go-sdk
+      
+  build_test_cli:
+    needs: check_code_changed
+    if: ${{ needs.check_code_changed.outputs.interopcc_changed == 'true' || needs.check_code_changed.outputs.gocli_changed == 'true' }}
+    runs-on: ubuntu-22.04
+    steps:
+    - uses: actions/checkout@v4.1.1
+
+    - name: Set up Go
+      uses: actions/setup-go@v4.0.0
+      with:
+        go-version: '1.20.2'
+
+    - name: Vendor
+      run: make run-vendor
+      working-directory: weaver/samples/fabric/go-cli
+
+    - name: Build
+      run: make build
+      working-directory: weaver/samples/fabric/go-cli
 
   unit_test_simplestate:
     needs: check_code_changed
@@ -119,6 +215,30 @@ jobs:
     - name: Test
       run: go test -v ./...
       working-directory: weaver/samples/fabric/simplestate
+
+  unit_test_satpsimpleasset:
+    needs: check_code_changed
+    if: ${{ needs.check_code_changed.outputs.interopcc_changed == 'true' || needs.check_code_changed.outputs.satpsimpleasset_changed == 'true' }}
+    runs-on: ubuntu-22.04
+    steps:
+    - uses: actions/checkout@v4.1.1
+
+    - name: Set up Go
+      uses: actions/setup-go@v4.0.0
+      with:
+        go-version: '1.20.2'
+
+    - name: Vendor
+      run: make run-vendor
+      working-directory: weaver/samples/fabric/satpsimpleasset
+
+    - name: Build
+      run: go build -v ./...
+      working-directory: weaver/samples/fabric/satpsimpleasset
+
+    - name: Test
+      run: go test -v ./...
+      working-directory: weaver/samples/fabric/satpsimpleasset
 
   unit_test_simpleasset:
     needs: check_code_changed
